### ISSUE TITLE
Printing characters from CodePage.CP437

### ISSUE THREAD

**Issue by sharkwheels** [BoboTiG/thermalprinter#11]
Hi! Probably a simple question, but can someone post an example of printing specific characters from CP437? Namely characters like the diamond (♦), heart (♥), etc? Do they have to be sent as bytes? Thanks!

**Comment by BoboTiG** [comment]
Ah yes, this is not obvious :)

The thing is that codepages are not very "standards". Have a look at the [specification document](https://thermalprinter.readthedocs.io/en/latest/_downloads/Embedded%20printer%20DP-EH600%20Technical%20Manual.pdf), there is a list of codepages and printable characters at the end. You will see that you will have to use the Katakana codepage (which is an alias to CP932).

I added some code into #12, what do you think?

**Comment by BoboTiG** [comment]
I will see to get/generate a complete list of printable characters by codepage (with associated hexadecimal code to use). It would ease the use for everyone :)

**Comment by BoboTiG** [comment]
@sharkwheels did you have time to test my code?
