### ISSUE TITLE
Letter 'P' being printed every time before anything else

### ISSUE THREAD

**Issue by pawelmalak** [BoboTiG/thermalprinter#15]
As in the title, every time I'm trying to print something, a new line with the letter 'P' is added. 

I tried the sample code from [README > Usage](https://github.com/BoboTiG/thermalprinter#usage) and got this as a result:

![IMG_2207](https://user-images.githubusercontent.com/24780509/92302618-cabbcb00-ef6d-11ea-8d6e-583043261640.jpg)

And later I tried to print only new lines with this code...
```python
from PIL import Image
from thermalprinter import *

with ThermalPrinter(port='/dev/serial0',baudrate=9600) as printer:
    printer.feed(5)
```

... with this as a result:

![IMG_2206](https://user-images.githubusercontent.com/24780509/92302643-0eaed000-ef6e-11ea-9863-c5bb09f6db58.jpg)

Any idea what might be causing it?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/thermalprinter/issues/15">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/thermalprinter/issues/15/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/thermalprinter/issues/15/pledge.svg">
</picture>
</a>

**Comment by zbyrek** [comment]
I have same issue, did you resolve that?

**Comment by pawelmalak** [comment]
Unfortunately, I did not. I tried different configurations and sample codes but I couldn't get around it and since it only was my side project I just gave up on it. Are you using it with Raspberry Pi by any chance?

**Comment by BoboTiG** [comment]
@pawelmalak, and @zbyrek, what is your printer model?

**Comment by archfurry** [comment]
Dear @BoboTiG ,
I experience that same problem with QR701 priter bought on [AliExpress](https://www.aliexpress.com/item/1005006015996675.html?spm=a2g0o.productlist.main.1.7c596koU6koUS8&algo_pvid=681538cd-a514-4d72-890e-60e62e766643&algo_exp_id=681538cd-a514-4d72-890e-60e62e766643-0&pdp_npi=4%40dis%21RUB%212630.16%211972.36%21%21%2125.27%2118.95%21%402103254117115743424894070eb7b1%2112000035335731466%21sea%21SRB%213754745505%21&curPageLogUid=LBiulfZsFW5R&utparam-url=scene%3Asearch%7Cquery_from%3A)
The fix from @zbyrek  works fine, no other side effects observed, although no characters other than ASCII are used.

**Comment by BoboTiG** [comment]
Can you share the firmware version of your printers? You can find it buy pressing the button on the printer while connecting the power.

**Comment by BoboTiG** [comment]
Thank you @archfurry, OOC where did you buy that printer?
