### ISSUE TITLE
Images are not being printed correctly

### ISSUE THREAD

**Issue by pawelmalak** [BoboTiG/thermalprinter#16]
I tried to print example code from [README > Usage](https://github.com/BoboTiG/thermalprinter#usage) and got text and barcode being printed properly: 

![IMG_2209](https://user-images.githubusercontent.com/24780509/92302772-0014e880-ef6f-11ea-913a-4c100aea0035.jpg)

But when I try to print any image I'm just getting bunch of random characters. I made sure that the image has correct size and that the baud rate is also correct.

![IMG_2210](https://user-images.githubusercontent.com/24780509/92302823-6d287e00-ef6f-11ea-9285-d7aee8e41d53.jpg)

I also tried to hardcode self._byte_Time as sugested in #9 

> I managed to get my images working by setting a hardcoded self._byte_Time 0.0005 (which is somewhat close to the default timing) rather than depending on the low sleep time set by my higher baudrate 115200.

but it didn't work in my case.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/thermalprinter/issues/16">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/thermalprinter/issues/16/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/thermalprinter/issues/16/pledge.svg">
</picture>
</a>

**Comment by BoboTiG** [comment]
I released the version [1.0.0](https://github.com/BoboTiG/thermalprinter/releases/tag/1.0.0) with a new code to print images. I close the issue since it's an old one. Just open a new issue on any other problem.
